CSRF_ENABLED = True
SECRET_KEY = 'r4i78fnwrfs7horo87v783ohg18eph0dfjfaohfr'

SITE = 'Sample'
FORM_DEFINITIONS = 'sample.json'
ODK_DB = 'odk_prod'
OPEN_HDS_DB = 'openhds'
DB_HOST = 'data-management.local'
DB_USER = 'data'
DB_PW = 'data'
USER = 'us'
PWD = 'pw'
MAX_REVISITS = '20'
REVISIT_RADIUS = '3'
BACK_REPORT_DAYS = '30'
